// This GUI file is generated by guibuilder version 4.2.1
//////////
f=figure('figure_position',[208,47],'figure_size',[1113,641],'auto_resize','on','background',[33],'figure_name','Graphic window number %d','dockable','off','infobar_visible','off','toolbar_visible','off','menubar_visible','off','default_axes','on','visible','off');
//////////
handles.dummy = 0;
handles.txt_Titulo=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Trajan','FontSize',[20],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.3651412,0.9086711,0.2363486,0.0631229],'Relief','default','SliderStep',[0.01,0.1],'String','Taller 1.- Grupo # 4','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_Titulo','Callback','')
handles.txt_TituloP1=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Impact','FontSize',[14],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0247934,0.7990033,0.2765014,0.0664784],'Relief','default','SliderStep',[0.01,0.1],'String','Función para Obtener el Factorial de un Número','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_TituloP1','Callback','')
handles.txt_Num=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Gotham','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0073462,0.7026578,0.1023324,0.0498339],'Relief','default','SliderStep',[0.01,0.1],'String','Ingrese el Número:','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_Num','Callback','')
handles.dato_fp1=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Bodoni','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.12764,0.6910299,0.1735537,0.0698007],'Relief','default','SliderStep',[0.01,0.1],'String','','Style','edit','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','dato_fp1','Callback','')
handles.btn_Calcular_P1=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[14],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0073462,0.60299,0.0964187,0.0498339],'Relief','default','SliderStep',[0.01,0.1],'String','Calcular','Style','pushbutton','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','btn_Calcular_P1','Callback','btn_Calcular_P1_callback(handles)')
handles.result_p1=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','off','FontAngle','normal','FontName','Bodoni','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.1221304,0.589701,0.184573,0.0863787],'Relief','default','SliderStep',[0.01,0.1],'String','','Style','edit','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','result_p1','Callback','')
handles.txt_Titulo_P2=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Impact','FontSize',[16],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0419325,0.4966777,0.2579763,0.0548173],'Relief','default','SliderStep',[0.01,0.1],'String','Números Primos ','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_Titulo_P2','Callback','')
handles.txt_descrip=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[13],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0492252,0.4385382,0.2525068,0.0365449],'Relief','default','SliderStep',[0.01,0.1],'String','Generar los 100 primeros números Primos','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_descrip','Callback','')
handles.btn_GenerarPP2=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0118505,0.0980066,0.0847767,0.2591362],'Relief','default','SliderStep',[0.01,0.1],'String','GENERAR','Style','pushbutton','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','btn_GenerarPP2','Callback','btn_GenerarPP2_callback(handles)')
handles.List_NumPrimos=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[1],'Max',[1],'Min',[0],'Position',[0.1011851,0.0265781,0.2023701,0.3737542],'Relief','default','SliderStep',[0.01,0.1],'String','#Lista de los números Primos','Style','listbox','Value',[1],'VerticalAlignment','middle','Visible','on','Tag','List_NumPrimos','Callback','List_NumPrimos_callback(handles)')
handles.txt_tituloP3=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Impact','FontSize',[20],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.4977211,0.7990033,0.4530538,0.0647841],'Relief','default','SliderStep',[0.01,0.1],'String','POLINOMIO DE TAYLOR','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_tituloP3','Callback','')
handles.txt_subtitulo1=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[14],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.8148952,0.7161462,0.1548587,0.06299],'Relief','default','SliderStep',[0.01,0.1],'String','VALORES A INGRESAR','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_subtitulo1','Callback','')
handles.txt_subt_p1=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.7967183,0.6528239,0.1248861,0.051495],'Relief','default','SliderStep',[0.01,0.1],'String','PUNTO A EVALUAR:','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_subt_p1','Callback','')
handles.puntoV1_P3=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.7985415,0.5664452,0.1759344,0.0614618],'Relief','default','SliderStep',[0.01,0.1],'String','','Style','edit','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','puntoV1_P3','Callback','')
handles.btn_PuntoV1=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.8240656,0.5016611,0.1276208,0.051495],'Relief','default','SliderStep',[0.01,0.1],'String','Calcular','Style','pushbutton','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','btn_PuntoV1','Callback','btn_PuntoV1_callback(handles)')
handles.txt_subt_p2=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.7985415,0.3986711,0.1267092,0.0548173],'Relief','default','SliderStep',[0.01,0.1],'String','ERROR A CALCULAR:','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_subt_p2','Callback','')
handles.ErrorV2_P3=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.8003646,0.3222591,0.1731996,0.0581395],'Relief','default','SliderStep',[0.01,0.1],'String','','Style','edit','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','ErrorV2_P3','Callback','')
handles.btn_ErrorV2=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.8331814,0.2524917,0.1175934,0.051495],'Relief','default','SliderStep',[0.01,0.1],'String','Calcular','Style','pushbutton','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','btn_ErrorV2','Callback','btn_ErrorV2_callback(handles)')
handles.txt_RespuestaP3=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','comic sans ms','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.8003646,0.1528239,0.0821787,0.0548173],'Relief','default','SliderStep',[0.01,0.1],'String','RESPUESTA:','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','txt_RespuestaP3','Callback','')
handles.errorT_P3=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','off','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.8176846,0.0813953,0.1649954,0.0598007],'Relief','default','SliderStep',[0.01,0.1],'String','','Style','edit','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','errorT_P3','Callback','')
handles.graficaTaylor= newaxes();handles.graficaTaylor.margins = [ 0 0 0 0];handles.graficaTaylor.axes_bounds = [0.359216,0.2475083,0.4201003,0.7060133];


f.visible = "on";


//////////
// Callbacks are defined as below. Please do not delete the comments as it will be used in coming version
//////////

function btn_Calcular_P1_callback(handles)
//Write your callback for  btn_Calcular_P1  here

endfunction


function btn_GenerarPP2_callback(handles)
//Write your callback for  btn_GenerarPP2  here

endfunction


function List_NumPrimos_callback(handles)
//Write your callback for  List_NumPrimos  here

endfunction


function btn_PuntoV1_callback(handles)
//Write your callback for  btn_PuntoV1  here

endfunction


function btn_ErrorV2_callback(handles)
//Write your callback for  btn_ErrorV2  here

endfunction


